UNSEEN_CLASSES = {
    "sketchy_1": [
        "cup", 
        "swan", 
        "harp", 
        "squirrel", 
        "snail", 
        "ray", 
        "pineapple", 
        "volcano", 
        "rifle", 
        "scissors", 
        "parrot", 
        "windmill", 
        "teddy_bear", 
        "tree", 
        "wine_bottle", 
        "deer", 
        "chicken", 
        "airplane", 
        "wheelchair", 
        "tank", 
        "umbrella", 
        "butterfly", 
        "camel", 
        "horse", 
        "bell"
    ],

    "sketchy_2": [
        "bat",
        "cabin",
        "cow",
        "dolphin",
        "door",
        "giraffe",
        "helicopter",
        "mouse",
        "pear",
        "raccoon",
        "rhinoceros",
        "saw",
        "scissors",
        "seagull",
        "skyscraper",
        "songbird",
        "sword",
        "tree",
        "wheelchair",
        "windmill",
        "window",
    ],

    "quickdraw": [
        "alarm_clock",
        "axe",
        "airplane", # bandage
        "bat",
        "car",
        "bread",
        "bus",
        "cake",
        "campfire",
        "cruise ship",
        "dolphin",
        "eiffel tower",
        "eyeglasses",
        "horse", #fire_hydrant
        "flower",
        "giraffe",
        "hamburger",
        "helicopter",
        "hot-air_balloon",
        "kangaroo",
        "tree", # map
        "megaphone",
        "moon",
        "motorcycle",
        "palm tree",
        "parrot",
        "raccoon",
        "sailboat",
        "skyscraper",
        "windmill",
    ],

    
    "tuberlin": [
        "helicopter",
        "wrist-watch",
        "mermaid",
        "mosquito",
        "pear",
        "couch",
        "hammer",
        "airplane",
        "house",
        "baseball bat",
        "toilet",
        "panda",
        "butterfly",
        "mug",
        "wineglass",
        "motorbike",
        "eyeglasses",
        "hot air balloon",
        "cup",
        "skull",
        "truck",
        "palm tree",
        "cell phone",
        "horse",
        "sailboat",
        "suv",
        "church",
        "floor lamp",
        "bus",
        "tv",
    ],
}


# Cross-dataset ZS-SBIR subsets used by ZSE-SBIR and SpLIP.  The source is
# Sketchy-1-Ext (100 seen / 25 unseen).  Starting from each target dataset's
# 30-class test split, categories already present in the 100 Sketchy-1 seen
# classes are removed.  This leaves S->T(21) and S->Q(11).
CROSS_DATASET_CLASSES = {
    ("sketchy_1", "tuberlin"): [
        "bus",
        "tractor",
        "suitcase",
        "streetlight",
        "telephone",
        "bottle opener",
        "canoe",
        "teacup",
        "laptop",
        "lighter",
        "brain",
        "t-shirt",
        "trombone",
        "windmill",
        "snowboard",
        "rollerblades",
        "parachute",
        "space shuttle",
        "bridge",
        "frying-pan",
        "horse",
    ],
    ("sketchy_1", "quickdraw"): [
        "scissors",
        "tree",
        "windmill",
        "feather",
        "campfire",
        "palm tree",
        "fire_hydrant",
        "beach",
        "megaphone",
        "cactus",
        "cake",
    ],
}
