UNSEEN_CLASSES = {
    "sketchy_1": [
        "cup", 
        "swan", 
        "harp", 
        "squirrel", 
        "snail", 
        "ray", 
        "pineapple", 
        "volcano", 
        "rifle", 
        "scissors", 
        "parrot", 
        "windmill", 
        "teddy_bear", 
        "tree", 
        "wine_bottle", 
        "deer", 
        "chicken", 
        "airplane", 
        "wheelchair", 
        "tank", 
        "umbrella", 
        "butterfly", 
        "camel", 
        "horse", 
        "bell"
    ],

    "sketchy_2": [
        "bat",
        "cabin",
        "cow",
        "dolphin",
        "door",
        "giraffe",
        "helicopter",
        "mouse",
        "pear",
        "raccoon",
        "rhinoceros",
        "saw",
        "scissors",
        "seagull",
        "skyscraper",
        "songbird",
        "sword",
        "tree",
        "wheelchair",
        "windmill",
        "window",
    ],

    "quickdraw": [
        "alarm_clock",
        "axe",
        "airplane", # bandage
        "bat",
        "car",
        "bread",
        "bus",
        "cake",
        "campfire",
        "cruise ship",
        "dolphin",
        "eiffel tower",
        "eyeglasses",
        "horse", #fire_hydrant
        "flower",
        "giraffe",
        "hamburger",
        "helicopter",
        "hot-air_balloon",
        "kangaroo",
        "tree", # map
        "megaphone",
        "moon",
        "motorcycle",
        "palm tree",
        "parrot",
        "raccoon",
        "sailboat",
        "skyscraper",
        "windmill",
    ],

    
    "tuberlin": [
        "helicopter",
        "wrist-watch",
        "mermaid",
        "mosquito",
        "pear",
        "couch",
        "hammer",
        "airplane",
        "house",
        "baseball bat",
        "toilet",
        "panda",
        "butterfly",
        "mug",
        "wineglass",
        "motorbike",
        "eyeglasses",
        "hot air balloon",
        "cup",
        "skull",
        "truck",
        "palm tree",
        "cell phone",
        "horse",
        "sailboat",
        "suv",
        "church",
        "floor lamp",
        "bus",
        "tv",
    ],
}


# Fixed cross-dataset ZS-SBIR subsets used for Sketchy-1-Ext as the source.
# Keep these protocol lists explicit: S->T uses 21 classes and S->Q uses 11.
CROSS_DATASET_CLASSES = {
    ("sketchy_1", "tuberlin"): [
        "airplane",
        "baseball bat",
        "bus",
        "butterfly",
        "cell phone",
        "cup",
        "floor lamp",
        "house",
        "horse",
        "mermaid",
        "mosquito",
        "mug",
        "palm tree",
        "panda",
        "skull",
        "suv",
        "toilet",
        "truck",
        "tv",
        "wineglass",
        "wrist-watch",
    ],
    ("sketchy_1", "quickdraw"): [
        "airplane",
        "cruise ship",
        "windmill",
        "horse",
        "bus",
        "eiffel tower",
        "cake",
        "parrot",
        "palm tree",
        "megaphone",
        "tree",
    ],
}
