UNSEEN_CLASSES = {
    "sketchy_1": [
        "cup", 
        "swan", 
        "harp", 
        "squirrel", 
        "snail", 
        "ray", 
        "pineapple", 
        "volcano", 
        "rifle", 
        "scissors", 
        "parrot", 
        "windmill", 
        "teddy_bear", 
        "tree", 
        "wine_bottle", 
        "deer", 
        "chicken", 
        "airplane", 
        "wheelchair", 
        "tank", 
        "umbrella", 
        "butterfly", 
        "camel", 
        "horse", 
        "bell"
    ],

    "sketchy_2": [
        "bat",
        "cabin",
        "cow",
        "dolphin",
        "door",
        "giraffe",
        "helicopter",
        "mouse",
        "pear",
        "raccoon",
        "rhinoceros",
        "saw",
        "scissors",
        "seagull",
        "skyscraper",
        "songbird",
        "sword",
        "tree",
        "wheelchair",
        "windmill",
        "window",
    ],

    "quickdraw": [
        "alarm_clock",
        "axe",
        "airplane", # bandage
        "bat",
        "car",
        "bread",
        "bus",
        "cake",
        "campfire",
        "cruise ship",
        "dolphin",
        "eiffel tower",
        "eyeglasses",
        "horse", #fire_hydrant
        "flower",
        "giraffe",
        "hamburger",
        "helicopter",
        "hot-air_balloon",
        "kangaroo",
        "tree", # map
        "megaphone",
        "moon",
        "motorcycle",
        "palm tree",
        "parrot",
        "raccoon",
        "sailboat",
        "skyscraper",
        "windmill",
    ],

    
    "tuberlin": [
        "helicopter",
        "wrist-watch",
        "mermaid",
        "mosquito",
        "pear",
        "couch",
        "hammer",
        "airplane",
        "house",
        "baseball bat",
        "toilet",
        "panda",
        "butterfly",
        "mug",
        "wineglass",
        "motorbike",
        "eyeglasses",
        "hot air balloon",
        "cup",
        "skull",
        "truck",
        "palm tree",
        "cell phone",
        "horse",
        "sailboat",
        "suv",
        "church",
        "floor lamp",
        "bus",
        "tv",
    ],
}


# Fixed seen-category distractors added to the unseen photo gallery for the
# subset-based GZS-SBIR evaluation.  Queries remain unseen-category sketches.
GENERALIZED_CLASSES = {
    "sketchy_2": [
        "airplane",
        "apple",
        "beetle",
        "bench",
        "candle",
        "couch",
        "deer",
        "dog",
        "elephant",
        "hedgehog",
        "horse",
        "kangaroo",
        "pickup_truck",
        "pig",
        "scorpion",
        "shark",
        "starfish",
        "table",
        "teapot",
        "tiger",
        "umbrella",
    ],
    "tuberlin": [
        "banana",
        "bee",
        "beer-mug",
        "bench",
        "bottle opener",
        "bulldozer",
        "chair",
        "crocodile",
        "elephant",
        "envelope",
        "fish",
        "flower with stem",
        "giraffe",
        "hamburger",
        "helmet",
        "hourglass",
        "human-skeleton",
        "ice-cream-cone",
        "key",
        "keyboard",
        "lion",
        "lobster",
        "mailbox",
        "monkey",
        "nose",
        "pen",
        "pickup truck",
        "potted plant",
        "pretzel",
        "pumpkin",
        "revolver",
        "satellite dish",
        "socks",
        "spider",
        "stapler",
        "t-shirt",
        "table",
        "teapot",
        "tennis-racket",
        "tent",
        "tooth",
        "trumpet",
        "umbrella",
        "wine-bottle",
    ],
}
